package images;

/**
 * An interface for ImageGenerating where images can be generated by users.
 *
 */
public interface ImageGenerator {

  /**
   * Generate the integer array representing the rainbow image.
   * 
   * @param height       the height of the rainbow image
   * @param width        the width of the rainbow image
   * @param isHorizontal if the rainbow stripe is horizontal
   * @return the 3D integer array representing the rainbow image
   */
  int[][][] rainbow(int height, int width, boolean isHorizontal);

  /**
   * Generate the integer array representing the checker board image.
   * 
   * @param heightBlock the number of blocks in height
   * @param widthBlock  the number of blocks in width
   * @param blockSize   the size of each block
   * @return the 3D integer array representing the checker board image
   */
  int[][][] checkBoard(int heightBlock, int widthBlock, int blockSize);

  /**
   * Generate the integer array representing the flag of France image.
   * 
   * @param height the height of the flag of France image
   * @param width  the width of the flag of France image
   * @return the 3D integer array representing the flag of France image
   */
  int[][][] flagFrance(int height, int width);

  /**
   * Generate the integer array representing the flag of Switzerland image.
   * 
   * @param width the width of the flag of Switzerland image
   * @return the 3D integer array representing the flag of Switzerland image
   */
  int[][][] flagSwiterland(int width);

  /**
   * Generate the integer array representing the flag of Norway image.
   * 
   * @param height the height of the flag of Norway image
   * @param width  the width of the flag of Norway image
   * @return the 3D integer array representing the flag of Norway image
   */
  int[][][] flagNorway(int height, int width);

  /**
   * Generate the integer array representing the flag of Greece image.
   * 
   * @param height the height of the flag of Greece image
   * @param width  the width of the flag of Greece image
   * @return the 3D integer array representing the flag of Greece image
   */
  int[][][] flagGreece(int height, int width);

}